### ISSUE TITLE
Pin Tab not working after Atom update

### ISSUE THREAD

**Issue by jbnv** [ArnaudRinquin/atom-zentabs#43]
Somehow the Pin tab command has just stopped working for me. The lock icon doesn't appear, and the tab that is supposed to be pinned gets closed anyway as more tabs are opened. This has just started being a problem for me, so I suspect it has something to do with the recent Atom update.

**Comment by klvs** [comment]
Experiencing the same issue. OSX 10.12.5 and using the Nuclide package

**Comment by andmos** [comment]
I found this project today, to bad it didn't work for me on Atom 1.19.1. 
Respecting the time issue on projects like this, so no hurry @ArnaudRinquin 👍

**Comment by hagabaka** [comment]
I think the problem is this selector is returning the "Project" tab and adding the `pinned` class to it, instead of the file tab the user right clicked:
```coffeescript
tab = $('.tab.right-clicked, .tab.active').first()
```
https://github.com/ArnaudRinquin/atom-zentabs/blob/master/lib/zentabs-controller.coffee#L83
Replacing it with just `'.tab.right-clicked'` should fix the problem, but I don't know how to test it yet.
